server:
  port: 8081
  servlet:
    context-path: /blog

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 600
  datasource:
    username: root
    password: 747478486@QQ.com
    url: jdbc:mysql://localhost:3306/blog?tinyInt1isBit=false&serverTimezone=UTC

logging:
  pattern:
    console: "%d - %msg%n"
  file:
    path: /log/blog-auth/

mybatis:
  type-aliases-package: com.lcp.blog.entity            # 定义所有操作类的别名所在包
  mapper-locations: classpath:**/mapper/*.xml     # 所有的mapper映射文件

#mybaatis分页插件pagehelper设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true